Doctor.create(username: "doctor_john", email: "john@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_ashley", email: "ashley@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_angela", email: "angela@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_joe", email: "joe@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_mike", email: "mike@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_charlie", email: "charlie@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_max", email: "max@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_rebecca", email: "rebecca@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_desiree", email: "desiree@medigrowth.com", password: "test", is_a_doctor: 1)
Doctor.create(username: "doctor_alisa", email: "alisa@medigrowth.com", password: "test", is_a_doctor: 1)


User.create(username: "snookie", email: "snookie@celebrity.com", password: "test", doctor_id: 1, is_a_doctor: 0)
User.create(username: "jenaniston", email: "jen@celebrity.com", password: "test", doctor_id: 1, is_a_doctor: 0)
User.create(username: "rihanna", email: "rihanna@celebrity.com", password: "test", doctor_id: 2, is_a_doctor: 0)
User.create(username: "bradpitt", email: "brad@celebrity.com", password: "test", doctor_id: 2, is_a_doctor: 0)
User.create(username: "taylorswift", email: "taylor@celebrity.com", password: "test", doctor_id: 2, is_a_doctor: 0)
User.create(username: "oprah", email: "oprah@celebrity.com", password: "test", doctor_id: 2, is_a_doctor: 0)
User.create(username: "tomhanks", email: "tomhanks@celebrity.com", password: "test", doctor_id: 2, is_a_doctor: 0)
User.create(username: "angelinajolie", email: "angelinajolie@celebrity.com", password: "test", doctor_id: 2, is_a_doctor: 0)
User.create(username: "katyperry", email: "katy@celebrity.com", password: "test", doctor_id: 3, is_a_doctor: 0)
User.create(username: "tomcruise", email: "tom@celebrity.com", password: "test", doctor_id: 3, is_a_doctor: 0)
User.create(username: "therock", email: "therock@celebrity.com", password: "test", doctor_id: 3, is_a_doctor: 0)
User.create(username: "ellen", email: "ellen@celebrity.com", password: "test", doctor_id: 4, is_a_doctor: 0)
User.create(username: "willsmith", email: "freshprince@celebrity.com", password: "test", doctor_id: 5, is_a_doctor: 0)
User.create(username: "mileycyrus", email: "miley@celebrity.com", password: "test", doctor_id: 5, is_a_doctor: 0)
User.create(username: "britneyspears", email: "britney@celebrity.com", password: "test", doctor_id: 6, is_a_doctor: 0)
User.create(username: "jenniferlopez", email: "jennifer@celebrity.com", password: "test", doctor_id: 6, is_a_doctor: 0)
User.create(username: "nickiminaj", email: "nicki@celebrity.com", password: "test", doctor_id: 7, is_a_doctor: 0)
User.create(username: "mattdamon", email: "matt@celebrity.com", password: "test", doctor_id: 7, is_a_doctor: 0)
User.create(username: "arianagrande", email: "ariana@celebrity.com", password: "test", doctor_id: 8, is_a_doctor: 0)
User.create(username: "adele", email: "adele@celebrity.com", password: "test", doctor_id: 9, is_a_doctor: 0)


Post.create(condition: "migraine", rating: 5, comments: "", user_id: 5, created_at: "2021-01-30 02:20:35.861721")
Post.create(condition: "migraine", rating: 0, comments: "", user_id: 5, created_at: "2021-02-01 02:20:35.861721")
Post.create(condition: "migraine", rating: 7, comments: "", user_id: 5, created_at: "2021-02-02 02:20:35.861721")

Post.create(condition: "weight", rating: 200, comments: "", user_id: 6, created_at: "2021-01-01 02:20:35.861721")
Post.create(condition: "weight", rating: 198, comments: "", user_id: 6, created_at: "2021-01-11 02:20:35.861721")
Post.create(condition: "weight", rating: 194, comments: "", user_id: 6, created_at: "2021-01-21 02:20:35.861721")
Post.create(condition: "weight", rating: 190, comments: "", user_id: 6, created_at: "2021-02-01 02:20:35.861721")

Post.create(condition: "pain", rating: 9, comments: "", user_id: 7, created_at: "2021-01-30 02:20:35.861721")
Post.create(condition: "pain", rating: 5, comments: "", user_id: 7, created_at: "2021-02-01 02:20:35.861721")

Post.create(condition: "diabetes", rating: 5, comments: "", user_id: 8, created_at: "2021-02-01 02:20:35.861721")